# use osrf noetic-desktop-full image and run image_view on /detected_aruco_frames also start recording rosbag make volume for storing rosbag mapped to the  ~/rosbags directory on host
# set rosbag name as date and time

version: '2'


services:
      image_view:
          image: osrf/ros:noetic-desktop-full
          container_name: image_view
          privileged: true
          volumes:
              - /tmp/.X11-unix:/tmp/.X11-unix
              - /dev:/dev
          environment:
              - DISPLAY
          command: rosrun image_view image_view image:=/detected_aruco_frames
          network_mode: host
  
      rosbag:
          image: osrf/ros:noetic-desktop-full
          container_name: rosbag
          privileged: true
          volumes:
              - ~/rosbags:/rosbags
          environment:
              - DISPLAY
          command: rosbag record -O /rosbags/$(date +%Y-%m-%d_%H-%M-%S) -a
          network_mode: host